name: waypoint-tp
version: "${version}"
main: com.example.waypointTp.WaypointTp
api-version: '1.21'
commands:
  wp:
    description: Waypoint commands
    usage: "/<command> [ui|set|tp|tpp|del|reload|give]\n/<command> set <name> [x y z] [yaw pitch] [world]"
    permission: waypoints.use    # ← この権限がある人が /wp を実行可能
    permission-message: You don't have permission.

permissions:
  waypoints.use:
    description: ウェイポイント機能を使う（/wp 実行権）
    default: true
  waypoints.create:
    description: 座標を登録（/wp set）
    default: true
  waypoints.delete:
    description: 座標を削除（UIの右クリック削除）
    default: true
  waypoints.tpp:
    description: プレイヤーの場所へテレポート（/wp tpp）
    default: true
  waypoints.reload:
    description: 設定/メッセージ再読み込み（/wp reload）
    default: op
  # ★ 追加：オープナー配布
  waypoints.opener:
    description: 自分にオープナーを配布（/wp give）
    default: true
  waypoints.opener.others:
    description: 他人にオープナーを配布（/wp give <player>）
    default: op
  waypoints.delete.any:       # ★ 追加
    description: 他人のウェイポイントも削除できる
    default: op               # OP のみ許可。完全禁止なら false